//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        private int id;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Facture = new HashSet<Facture>();
        }

        public Client(int id, string nom, string prenom, string adresse, string genre, string status, int telephone)
        {
            this.id = id;
            Nom = nom;
            Prenom = prenom;
            Adresse = adresse;
            Genre = genre;
            Status = status;
            Telephone = telephone;
        }

        public int Id_client { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Adresse { get; set; }
        public string Genre { get; set; }
        public string Status { get; set; }
        public Nullable<int> Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Facture { get; set; }
        public bool IsNull()
        {
            return this == null;
        }
    }
}
