//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int Id { get; set; }
        public Nullable<int> Montant_total { get; set; }
        public Nullable<int> Id_client { get; set; }
        public Nullable<int> Id_chambre { get; set; }
        public Nullable<int> Id_service { get; set; }
    
        public virtual Chambre Chambre { get; set; }
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
