//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Facture = new HashSet<Facture>();
        }
    
        public int Id_service { get; set; }
        public string Nom_service { get; set; }
        public Nullable<int> Prix_unitaire { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Id_chambre { get; set; }
    
        public virtual Chambre Chambre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Facture { get; set; }
        public bool IsNull()
        {
            return this == null;
        }
    }
}
